// apps/desk-react/src/app/app.tsx
import * as React from 'react';
import { Component } from 'react';

import './app.scss';

export class App extends Component {
  render() {
    const title = 'desk-react';
    return (
      <div>
        <div style={{ textAlign: 'center' }}>
          <h1>Welcome to {title}!</h1>
          <img
            width="450"
            src="https://raw.githubusercontent.com/nrwl/nx/master/nx-logo.png"
          />
        </div>
        <p>
          This is a React app built with <a href="https://nx.dev">Nx</a>.
        </p>
        <p>
          🔎 **Nx is a set of Angular CLI power-ups for modern development.**
        </p>
        <h2>Quick Start & Documentation</h2>
        <ul>
          <li>
            <a href="https://nx.dev/getting-started/what-is-nx">
              30-minute video showing all Nx features
            </a>
          </li>
          <li>
            <a href="https://nx.dev/tutorial/01-create-application">
              Interactive tutorial
            </a>
          </li>
        </ul>
      </div>
    );
  }
}

// apps/desk/src/app/app.component.ts
import { Component } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { Message } from "@desk/api-interface";

@Component({
  selector: "desk-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent {
  hello$ = this.http.get<Message>("/api/hello");
  constructor(private http: HttpClient) {}
}

<div style="text-align:center">
  <h1>Welcome to desk!</h1>
  <img
    width="450"
    src="https://raw.githubusercontent.com/nrwl/nx/master/nx-logo.png"
  />
</div>
<div>Message: {{ hello$ | async | json }}</div>
